// Mejoras de control de días y registro de decisiones.
if (!data.holidays) data.holidays = [];
let holidayMonth = new Date();
function isoDate(date) { return date.toISOString().slice(0,10); }
function pendingDays(userId, periodId) { return data.requests.filter(r => r.userId === userId && (r.periodId || 1) === periodId && status(r)[1] === 'pending').flatMap(r => r.days); }

calendar = function () {
  usePeriod(); const p=period(),y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,total=new Date(y,m+1,0).getDate(),approved=periodDays(currentUserId,selectedPeriod),pending=pendingDays(currentUserId,selectedPeriod),today=isoDate(new Date());
  $('#period-select').innerHTML=data.periods.map(x=>`<option value="${x.id}">${x.name} · ${x.start} a ${x.end}</option>`).join('');$('#period-select').value=selectedPeriod;$('#month-label').textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(first);let html=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<div class="weekday">${x}</div>`).join('')+'<div class="day empty"></div>'.repeat(offset);
  for(let n=1;n<=total;n++){const date=new Date(y,m,n),d=isoDate(date),weekend=date.getDay()===0||date.getDay()===6,past=d<today,holiday=data.holidays.includes(d),isApproved=approved.includes(d),isPending=pending.includes(d),locked=weekend||past||holiday||isApproved||isPending||d<p.start||d>p.end;const cls=isApproved?'approved':isPending?'pendingday':holiday?'holiday':past?'pastday':'';html+=`<button type="button" data-day="${d}" class="day ${cls} ${chosen.includes(d)?'selected':''}" ${locked?'disabled':''}>${n}</button>`}$('#calendar').innerHTML=html;const spent=approved.length,left=p.days-spent;$('#policy-message').textContent=`${p.name}: tienes ${Math.max(left,0)} de ${p.days} días disponibles. Periodo: ${p.start} al ${p.end}.`;$('#selection-info').textContent=chosen.length?`${chosen.length} día(s) hábil(es) seleccionado(s).`:'No has elegido días todavía.';
};
summary = function () { const pending=data.requests.filter(r=>r.userId===currentUserId&&status(r)[1]==='pending').flatMap(r=>r.days).length,approved=approvedDays(currentUserId).length,remaining=data.periods.reduce((sum,p)=>sum+Math.max(p.days-periodDays(currentUserId,p.id).length,0),0),mine=data.requests.filter(r=>r.userId===currentUserId);$('#pending-count').textContent=pending;$('#approved-count').textContent=approved;$('#days-count').textContent=remaining;$('#my-balance').innerHTML=data.periods.map(p=>{const spent=periodDays(currentUserId,p.id).length;return `<div><span>${p.name}</span><strong>${Math.max(p.days-spent,0)}</strong><small>días hábiles restantes · ${spent} aprobados</small></div>`}).join('');$('#my-requests').innerHTML=mine.length?mine.sort((a,b)=>b.id-a.id).map(r=>{const[s,c]=status(r),p=data.periods.find(x=>x.id===(r.periodId||1));return `<article class="request"><div class="request-head"><strong>${dates(r.days)}</strong><span class="status ${c}">${s}</span></div><small>${p?.name||'Periodo 1'}${r.note?` · ${esc(r.note)}`:''}${r.rejectReason?` · Motivo: ${esc(r.rejectReason)}`:''}</small></article>`}).join(''):'<p class="empty">No hay solicitudes.</p>'};
function holidayCalendar(){const y=holidayMonth.getFullYear(),m=holidayMonth.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,total=new Date(y,m+1,0).getDate();$('#holiday-month-label').textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(first);let html=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<div class="weekday">${x}</div>`).join('')+'<div class="day empty"></div>'.repeat(offset);for(let n=1;n<=total;n++){const date=new Date(y,m,n),d=isoDate(date),weekend=date.getDay()===0||date.getDay()===6,marked=data.holidays.includes(d);html+=`<button type="button" data-holiday="${d}" class="day ${marked?'holiday holiday-selected':''}" ${weekend?'disabled':''}>${n}</button>`}$('#holiday-calendar').innerHTML=html}
const baseSuperView=superView;superView=function(){baseSuperView();holidayCalendar()};
$('#holiday-previous').onclick=()=>{holidayMonth.setMonth(holidayMonth.getMonth()-1);holidayCalendar()};$('#holiday-next').onclick=()=>{holidayMonth.setMonth(holidayMonth.getMonth()+1);holidayCalendar()};$('#holiday-calendar').addEventListener('click',e=>{const b=e.target.closest('[data-holiday]');if(!b)return;const d=b.dataset.holiday;data.holidays=data.holidays.includes(d)?data.holidays.filter(x=>x!==d):[...data.holidays,d];save();holidayCalendar()});
$('#admin-list').addEventListener('click',e=>{const b=e.target.closest('[data-vote]');if(!b)return;e.stopImmediatePropagation();const r=data.requests.find(x=>x.id===Number(b.dataset.request)),me=user();let reason='';if(b.dataset.vote==='no'){reason=prompt('Escribe el motivo del rechazo:');if(reason===null)return;if(!reason.trim())return alert('Debes indicar un motivo para rechazar.')}r.decisions[me.id]=b.dataset.vote;r.rejectReason=reason.trim();r.log=[{adminName:me.name,decision:b.dataset.vote,date:new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date())}];save();render()},{capture:true});
